/** Shared types used by both the client and the /api routes. */

export type MessageRole = "user" | "assistant";

export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  /** Chain-of-thought emitted by reasoning models such as qwen3. Optional. */
  reasoning?: string;
  createdAt: number;
  /** Set when this assistant turn is an error notice rather than a real reply. */
  isError?: boolean;
  /** Base64-encoded images attached to this message (user uploads or vision input). */
  images?: string[];
  /** Extracted text from an uploaded file (PDF, TXT, etc.). */
  fileAttachment?: { name: string; text: string };
  /** Base64-encoded image generated by the image generation sidecar. */
  generatedImage?: string;
}

export interface Conversation {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
  /**
   * Reserved for future project workspaces. Always null in v1, but persisted
   * so existing conversations survive the migration.
   */
  projectId: string | null;
}

/** Minimal message shape accepted by /api/chat and forwarded to Ollama. */
export interface WireMessage {
  role: MessageRole;
  content: string;
  /** Base64-encoded images for vision models. */
  images?: string[];
}

export interface ChatRequestBody {
  messages: WireMessage[];
  model?: string;
  temperature?: number;
  /** Optional user override appended to the built-in Mahdee AI system prompt. */
  customInstructions?: string;
  /**
   * Let the model reason at length before answering. Much slower — it can
   * generate ten times as many tokens — so this is off by default.
   */
  deepThinking?: boolean;
  /** Max tokens to generate per reply. 0 = unlimited. */
  numPredict?: number;
  /** Number of recent messages sent as context. */
  contextMessages?: number;
  /** Text extracted from an uploaded file, appended to the last user message. */
  fileAttachment?: { name: string; text: string };
  /** Number of CPU threads for Ollama inference. */
  numThread?: number;
}

/** One newline-delimited JSON event from the /api/chat stream. */
export type ChatStreamEvent =
  | { type: "delta"; text: string }
  | { type: "reasoning"; text: string }
  | { type: "done"; durationMs: number | null; model?: string }
  | { type: "error"; error: string; code: ChatErrorCode };

export type ChatErrorCode =
  | "bad_request"
  | "ollama_unreachable"
  | "model_missing"
  | "timeout"
  | "upstream_error";

export interface ChatErrorResponse {
  error: string;
  code: ChatErrorCode;
}

export interface HealthResponse {
  online: boolean;
  /** True when the configured default model is installed on the Ollama host. */
  modelAvailable: boolean;
  model: string;
  models: string[];
  message: string;
}

export interface ImageGenerationRequestBody {
  prompt: string;
  width?: number;
  height?: number;
  /** Overrides the server's default sidecar URL for this request. */
  sidecarUrl?: string;
}

export interface ImageGenerationSuccessResponse {
  image: string;
}

/** Response from the sidecar's /health endpoint, proxied by GET /api/generate-image. */
export interface ImageServiceHealth {
  status: "ready" | "loading" | "offline" | string;
  message?: string;
}

export interface AppSettings {
  model: string;
  temperature: number;
  customInstructions: string;
  showReasoning: boolean;
  /** Off by default: trades answer depth for a roughly 10x faster reply. */
  deepThinking: boolean;
  /** Max tokens to generate per reply. 0 = unlimited. Lower = faster. */
  numPredict: number;
  /** Number of recent messages sent as context. Fewer = faster prefill. */
  contextMessages: number;
  /** Enable image generation via Python sidecar. */
  imageGenerationEnabled: boolean;
  /** URL of the Python image generation sidecar. */
  imageGenerationUrl: string;
  /** Number of CPU threads for Ollama. Higher = faster on multi-core. */
  numThread: number;
}
